# Generated by Django 2.2.7 on 2019-12-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odsb', '0004_sp'),
    ]

    operations = [
        migrations.CreateModel(
            name='constore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('confirm', models.IntegerField()),
            ],
        ),
    ]
