# Generated by Django 2.2.7 on 2019-12-21 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odsb', '0005_constore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='email',
            new_name='username',
        ),
    ]
