# Generated by Django 2.2.7 on 2019-12-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odsb', '0006_auto_20191221_0852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_for', models.CharField(max_length=100)),
                ('overall', models.CharField(max_length=20)),
                ('idea', models.TextField()),
                ('given_date', models.DateField(auto_now=True)),
                ('given_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
