# Generated by Django 2.2.7 on 2019-12-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odsb', '0003_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='SP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.TextField()),
                ('email', models.CharField(max_length=200)),
            ],
        ),
    ]
