# Generated by Django 2.2.7 on 2019-12-23 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odsb', '0009_remove_suggestions_given_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestions',
            name='type_id',
        ),
    ]
