# Generated by Django 2.2.7 on 2019-12-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odsb', '0010_remove_suggestions_type_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestions',
            name='suggestion_for',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
