# Generated by Django 2.2.7 on 2019-12-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odsb', '0011_suggestions_suggestion_for'),
    ]

    operations = [
        migrations.CreateModel(
            name='POST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_from', models.CharField(max_length=100)),
                ('poster_id', models.CharField(max_length=100)),
                ('idea', models.TextField()),
                ('given_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
