# Generated by Django 2.2.7 on 2020-01-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odsb', '0013_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
