# Generated by Django 2.2.7 on 2020-01-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odsb', '0015_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestions',
            name='giver_id',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
