# Generated by Django 2.2.7 on 2020-01-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odsb', '0016_suggestions_giver_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestions',
            name='name',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
