# Generated by Django 2.2.7 on 2020-01-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odsb', '0017_suggestions_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
